
#include "ServiceAdmin.h"
#include <string>
#include <windows.h>


Service::Service(Repo &repoEvents, Repo &repoUser) {
    /*
     * Constructor of Service Class, which takes as parameters two Repo objects for admins and users
     * and generates the events
     * */
    this->repo = repoEvents;
    this->repo.generateEvents();
    this->repoUser = repoUser;
}

Service::~Service() = default;

void Service::addEvent(const string &title, const string &description, const string &date, const string &time,
                       int peopleGoing, const string& link) {
    /*
     * Add Event function takes all fields of an Event from UI and creates an Event object
     * that is added to the admin repo
     * Function also creates a date and a time object from the strings received as parameters
     * */
    Date date1(date);
    Time time1(time);
    Event event(title, description, date1, time1, peopleGoing, link);
    this->repo.addEvent(event);
}

void Service::removeEvent(const string &title, const string &description, const string &date,
                          const string &time, int peopleGoing, const string &link) {
    /*
     * Function removes an event from the admin repo. It takes all fields of an event object as params
     * and creates an event object that is removed from the repo by calling the removeEvent function
     * */
    Date date1(date);
    Time time1(time);
    Event event(title, description, date1, time1, peopleGoing, link);
    this->repo.removeEvent(event);
}

void Service::updateEvent(const std::string &oldTitle, const std::string &oldDescription, const std::string &titleNew,
                          const std::string &descriptionNew, const std::string &date, const std::string &time,
                          int peopleGoingNew, const std::string &link) {

    /*
     * function takes params all fields of an event obj and creates an event object that is updated with the new fields
     * the old event object is also created and passed as a param to the updateEvent function from repo
     * */
    Date dateNew(date);
    Time timeNew(time);
    Event eventNew(titleNew, descriptionNew, dateNew, timeNew, peopleGoingNew, link);
    Event eventOld(oldTitle, oldDescription, Date(), Time(), 0, "");
    this->repo.updateEvent(eventOld, eventNew);
}

int Service::length() const {
    return this->repo.length();
}

Event Service::getElement(int index) const {
    return this->repo.getElement(index);
}

Event Service::getCurrent() const {
    return this->repo.getCurrent();
}

void Service::next() {
    this->repo.next();
}

void Service::previous() {
    this->repo.previous();
}

string Service::getAllAdmin() {
    return this->repo.getAll();
}

string Service::getAllUser() {
    return this->repoUser.getAll();
}

string Service::userDisplayEventStart(int month) {
    /*
     * This function initiates the start of the user display event function by setting the current element to the
     * beginning of the list and then calling the userDisplayEvent function from repo
     * It returns the string generated by the repo function
     * */
    this->repoUser.setStart();
    return this->repo.userDisplayEvent(month);
}

string Service::userDisplayEventNext(int month) {
    /*
     * Standard user display event function, same as before but no initialization, starting from element at the position
     * this->current
     * */
    return this->repo.userDisplayEvent(month);
}

void Service::userParticipate() {
    /*
     * The function adds the current event to the user repo and increases the number of people going to the event
     * in the admin repo
     * */
    this->repoUser.addEvent(getCurrent());
    this->repo.userParticipate();
}

void Service::userRemoveParticipation(const string &title, const string &description, const string &date,
                                      const string &time, int peopleGoing, const string &link) {
    /*
     * Function takes all fields of an event object and creates an event object that is removed from the user repo
     * and decreases the number of people going to the event in the admin repo
     * */
    Event event(title, description, Date(date), Time(time), peopleGoing, link);
    this->repoUser.removeEvent(event);
    this->repo.userRemoveParticipation();
}

void Service::userOpenLink(Event event) {
    /*
     * Function takes an event object, extracts the link field and opens the link in the default browser
     * */
    string link = this->repo.getLink(event);
    ShellExecuteA(NULL, "open", link.c_str(), NULL, NULL, SW_SHOWNORMAL);
}